### ISSUE TITLE
[feature-request] Add some lua bindings for a few toolkits from CMSIS

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/frame-codebase#134]
The CMSIS library already used by Frame comes with optimized functions for various operations including classical DSP and Neural Networks. This could i.e. be used as preprocessing for audio:

https://arm-software.github.io/CMSIS-NN/latest/index.html
https://arm-software.github.io/CMSIS-DSP/latest/index.html

Having them in the firmware without even doing anything with them would let users experiment with their own features, i.e. low-res video or audio processing could eventually fit.

**Comment by rohitrathnam** [comment]
We can add math operations, but not sure how to implement the vector ones. It expects pointers, and the overhead to go in/out from lua table to C array would probably kill any gains. Any ideas?

**Comment by josuah** [comment]
CMSIS-NN and CMSIS-DSP have a lot of content... Maybe some very practical use-cases will enlight us about what we could try to add.

A few audio ideas:
- Audio compression, allowing to stream audio in real-time along with image. Low-latency audio can help for continuous capture.
- FFT if that fits. It might take a bit of room!

A few image ideas:
- Black/white filter for image before JPEG compression (then it compresses more, and the MCU cannot have access to the image before compressoin). Even if keeping RGB colors for ease of implementation, it might still compress more.
- Image cropping/resizing, not complex to do in software, but still some large volume of pixels.
- A tiny bit of ISP for tweaking the brightness/contrast/saturation manually, i.e. just work on a single pixel at a time.
- Kernels <https://en.wikipedia.org/wiki/Kernel_(image_processing)>, some of which might reduce compressed size

Some might require a lot of work, a lot of resources, but hopefully some are low-hanging fruits.

**Comment by josuah** [comment]
CMSIS might not be a good target when the BUS is SPI... We have our answer! Thank you! :)
