### ISSUE TITLE
[feature request] Video input over Bluetooth

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/frame-codebase#152]
This is a discussion to explore all the ways to implement video transfer over Bluetooth towards Frame display.

The 2 point that could throttle the transfer might be:
- Phone <---Bluetooth---> MCU communication
- MCU <---SPI---> FPGA communication

As well as amount of processing on the MCU and FPGA.

A few evoked solutions are:

- JPEG decoder counterpart to the encoder
- Use the bitmap library to stream the kind of data the FPGA can use, in 16-colors mode, updating the palette at every frame

For reference, the absolute maximum that is possible to achieve on an nRF52840 with Bluetooth 5:
https://www.youtube.com/watch?v=K1ItqEZ2_tw

**Comment by josuah** [comment]
To illustrate what different resolution and color mode mean in practice:
None of these were confirmed to be possible yet!

400x400 full RGB888:
![image_400_888](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/d0548422-a563-4223-8553-fdb09de43c02)

400x400 16 indexed colors:
![image_400_16i](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/0c31f462-6448-45ab-bdcd-1a2c4139aefc)

200x200 full RGB888:
![image_200_888](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/fdeafc5f-736d-43b1-ae80-251072d2823b)

200x200 16 indexed colors:
![image_200_16i](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/8ba8d492-7642-4450-ae6a-9db9a3625e78)

100x100 full RGB888:
![image_100_888](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/f0be51b6-0ab8-4368-a749-f562eaad3fcb)

100x100 16 indexed colors:
![image_100_16i](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/097e008c-fbd0-4425-afaa-c453923745e4)

**Comment by josuah** [comment]
Here is what could be done for the Monocle:
![output](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/ec8327d2-b89e-4ffb-9705-ede1e42171bf)

Not yet tested on the hardware.

**Comment by josuah** [comment]
This could be achieved on hardware on the Monocle
![mpv-shot0008](https://github.com/brilliantlabsAR/frame-codebase/assets/55351021/4edf762b-672b-49f4-912c-0c243479b718)

As seen above, still limitations that depend on the complexity of the image.

**Comment by rohitrathnam** [comment]
Deep dive into how JPEG works: [Everything You Need to Know About JPEG Tutorial Series](https://youtube.com/playlist?list=PLpsTn9TA_Q8VMDyOPrDKmSJYt1DLgDZU4&si=FlCXh7XJDXtBtLwd)
Leaving this here for future reference

**Comment by rmetchev** [comment]
Git repo to with the video series, used as reference for encoder.
https://github.com/dannye/jed

**Comment by rohitrathnam** [comment]
Quick update, the EBR/LUT resources are almost full so it's unlikely we can support both JPEG decode and encode at the same time

**Comment by josuah** [comment]
If two identical bitstreams can fit on the flash, this means it is possible to restart the FPGA at runtime with the alternative bitfile to cycle through features as the API uses them?

I think the LZO-compressed image was still quite large already though...

**Comment by josuah** [comment]
Some feedback suggests to investigate the https://multimedia.cx/mirror/idroq.txt codec widely used on inexpensive (read: low-resource, low-complexity codec), high volume game consoles.

https://discord.com/channels/963222352534048818/984966420603482182/1240281670939050075
