### ISSUE TITLE
[feature-request] Audio compression

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/frame-codebase#200]
Eventually addressed by #81 an audio compression library would allow real-time audio streaming, unlocking features like live translation/transcription.

The nRF53840 is the [reference kit](https://www.nordicsemi.com/Products/Development-hardware/nRF5340-Audio-DK) for Auracast/Bluetooth Low Energy Audio.
The nRF52840 is lacking a dual PLL required to do stereo, so is not the reference kit, but could still work for mono on CPU.

**Comment by siliconwitch** [comment]
Streaming audio already works at 8khz-8bit in realtime. The user can even bump the quality up a little more if they wanted to, and there are options in Lua to do this. This quality seems to work great with OpenAI whisper and other transcription services so we figure it's good enough. Additional audio compression libraries would probably take up precious flash and ram 

LZ4 could also be an option but I don't think it'll work great for audio. Note that the library planned in #81 will only be for decompression, not compression (I'll update that issue with the correction)
