### ISSUE TITLE
[feature request] Bluetooth Central role support

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/frame-codebase#221]
Connecting to accessories such as a keyboard or a mouse requires the Bluetooth Central implemented.

The hardware supports it, but not the software.

- https://github.com/brilliantlabsAR/monocle-micropython/issues/134

Suggested here:
https://discord.com/channels/963222352534048818/984966420603482182/1251157875771052143

**Comment by josuah** [comment]
Suggested by email

**Comment by siliconwitch** [comment]
This would become a really massive library to support everything so it's not planned. HID and maybe some other select profiles could be added though. I think that would cover things like that ring
