### ISSUE TITLE
[feature request] Turn Frame off without the dock

### ISSUE THREAD

**Issue by One-nb** [brilliantlabsAR/frame-codebase#223]
User wants to effectively turn Frame off without the dock. The sleep setting becomes impossible when placed somewhere in motion, e.g. pocket. 

Related:
https://github.com/brilliantlabsAR/frame-codebase/issues/147

Suggested from:
https://discord.com/channels/963222352534048818/984966420603482182/1251302847040192736

**Comment by siliconwitch** [comment]
Unfortunately then there'd be no way to turn Frame back on. 

A way around this is the use the current `frame.sleep()` function, but then on startup, use the IMU as a filter to detect the orientation. If Frame is in a sideways orientation, just call `frame.sleep()` again
