### ISSUE TITLE
[feature request] Cast the display of a phone

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/frame-codebase#224]
While the communication is Bluetooth, a protocol that does incremental drawing would allow to repaint only a small region at a time by comparing with the previous frame.

This does not play well with scrolling or animations, but a filter could be added to wait that the phone screen becomes still before sending the new frame, as a list of pixel that changed.

**Comment by siliconwitch** [comment]
This is already possible using the pixel draw command `frame.display.bitmap()`. API info coming soon
