### ISSUE TITLE
[feature request] screenshot: download the framebuffer back

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/frame-codebase#225]
The FPGA acts as a GPU engine that draws display commands.

For developers as well as users, it can be interesting to expose an export interface for the framebuffer, and recover it over Bluetooth to effectively take a screenshot.

**Comment by siliconwitch** [comment]
Planning to have a simulator instead. The size of the frame buffer is quite big so would take a while to send over bluetooth
