### ISSUE TITLE
Fix lua_file_write() with binary data

### ISSUE THREAD

**Issue by tremblin** [brilliantlabsAR/frame-codebase#261]
Writing binary data that potentially contains '\x00' bytes is not properly written to a file with frame.file.write():

Looking briefly at the code, i think the issue is at

https://github.com/brilliantlabsAR/frame-codebase/blob/2e2a01ef91b7bc854987e0e7c35d117830ac3371/source/application/lua_libraries/file.c#L279

if the LUA string contains '\x00' bytes the length to be written is not 'strlen(string)', but should be 'expected_length'.

to verify, send the following command string:

```
a="\x00";f=frame.file.open("/test.dat", "write");f:write(a);f:close()
```

**Comment by siliconwitch** [comment]
Great catch! I'll fix this right away
