### ISSUE TITLE
Pink vertical lines on photos from Frame leads to bad image recognition performance

### ISSUE THREAD

**Issue by CitizenOneX** [brilliantlabsAR/frame-codebase#284]
At least as early as September 14th issues were reported:
![image](https://github.com/user-attachments/assets/363b47b0-eb93-44d9-9265-81c4c20f3f91)

As a result, numerous users are reporting that Noa is unable to make sensible descriptions of what it's seeing. I also see the issue in simple vision apps - this particular banding in the image really throws off the classifier models.

Back on August 6 it was definitely fine:
![image](https://github.com/user-attachments/assets/f4bce917-b6d4-47cd-a52d-3e4922f6607b)

- The pink vertical lines issue looks to have been introduced with the **big camera firmare update on September 11:** (https://github.com/brilliantlabsAR/frame-codebase/releases/tag/v24.255.0646)

But with just this date range for completeness it could also possibly be:

- [Sep 4 Release v24.248.0928](https://github.com/brilliantlabsAR/frame-codebase/releases/tag/v24.248.0928)
- [Aug 28 Release v24.241.0836](https://github.com/brilliantlabsAR/frame-codebase/releases/tag/v24.241.0836)
- [Aug 15 Release v24.227.1307](https://github.com/brilliantlabsAR/frame-codebase/releases/tag/v24.227.1307)
- [Aug 8 Release v24.220.1445](https://github.com/brilliantlabsAR/frame-codebase/releases/tag/v24.220.1445)

**Comment by siliconwitch** [comment]
Should now be fixed with the latest release. Thanks for the help with debugging!

**Comment by PhilShaw852** [comment]
I have the same issue with the python SDK v1.2.2, will this be updated too?
